### ISSUE TITLE
fastboot menu in screen broken

### ISSUE THREAD

**Issue by lexcorp** [geo-stark/remote-fastboot#1]
I have a robot with Android, its screen is two ips displays (its eyes) when I restart in fastboot mode the menu is not displayed. It would be the equivalent of a broken phone screen. With this tool can I access the fastboot menu?

![alpha-mini-humanoid-educational](https://github.com/geo-stark/remote-fastboot/assets/5751288/b076fe1d-9d70-48d9-9638-246e8ba44e76)

![ALPHA-MINI-1](https://github.com/geo-stark/remote-fastboot/assets/5751288/c250d47e-1bc4-40ea-b9b9-57c3f10a1c03)

**Comment by geo-stark** [comment]
What you call fastboot menu actually is the recovery mode. Fastboot may work in recovery mode at once or may be started from recovery menu or it may be a separate device mode for fastboot.
In the latter case it has own enter procedure (e.g. another combination of button) and it doesn't have to display anything. All this is device-specific.

Anyway this tool won't help. It's intended to share usb fastboot connection over network.
